"""Plain-language goal in, ranked owned cards out, each with a stated reason.

Two commitments from spec section 6.4 shape this:

* **Every result carries a reason.** A ranked list with no explanation is a
  list you have to re-derive by reading 50 cards.
* **Weak matches are shown with their weakness named, not hidden.** A 54% match
  labelled "surfaced because it is ramp, not because it matches the theme" is
  more useful than silence, because it tells you what the search actually did.

Reasons are derived from concrete signals — similarity, what the card does,
colour fit, whether it is already committed — never generated by a model. A
made-up reason is worse than no reason.
"""
from __future__ import annotations

import re
import sqlite3
from typing import Any

from . import embeddings

# What a card does, read off its oracle text. Deliberately conservative: a
# missed role shows up as a quieter reason, a wrong one is a lie.
ROLES: tuple[tuple[str, str], ...] = (
    # NOTE: matching happens against lowercased text, so mana symbols must be
    # lowercase here. With [WUBRGC] the single most common ramp line in Magic,
    # "Add {G}", matched nothing and every mana dork was invisible.
    ("ramp", r"search your library for a[n]? (basic )?land|add \{[wubrgc0-9]\}|"
             r"add [a-z]+ mana|put .* lands? onto the battlefield|adds an additional"),
    ("card draw", r"\bdraw(s)? (a|two|three|X|that many) card"),
    ("tutor", r"search your library for a card|search your library for a creature|"
              r"search your library for an? (artifact|enchantment|instant|sorcery)"),
    ("removal", r"destroy target|destroy another target|exile target|"
                r"target creature gets -|deals? \d+ damage to target|"
                r"target (creature|player) sacrifices|return target .* to (its|their) owner"),
    ("board wipe", r"destroy all|exile all|each creature gets -|"
                   r"all creatures get -\d+/-\d+"),
    ("counterspell", r"counter target"),
    ("recursion", r"return target .* from your graveyard|"
                  r"return .* card from your graveyard to your hand|"
                  r"return it to the battlefield"),
    # Not just activated outlets: "as an additional cost, sacrifice a creature"
    # is the same idea, and demanding a colon told Eaten Alive it was not a
    # sacrifice card.
    ("sacrifice", r"sacrifice (a|an|another|two|three|X|it\b)"),
    ("token maker", r"create (a|two|three|X|that many|\d+) .*token"),
    ("counters", r"\+1/\+1 counter"),
    ("lifegain", r"you gain \d+ life|gain that much life|gains? life"),
    ("protection", r"hexproof|indestructible|protection from|shroud|"
                   r"can't be countered"),
    ("untapper", r"untap target|untap all|untap it"),
    ("cost reduction", r"costs? \{\d+\} less to cast|spells you cast cost"),
    ("evasion", r"\bflying\b|\btrample\b|can't be blocked|\bmenace\b|\bunblockable\b"),
)

# The same roles, but recognised in plain language rather than rules text.
# A goal says "dump a load of mana into a finisher"; a card says "add {G}".
# Reading the goal with the card patterns above matched nothing, so the
# "which is what you asked for" half of every reason never fired.
GOAL_PATTERNS: tuple[tuple[str, str], ...] = (
    ("ramp", r"\bramp\b|\bmana\b|accelerat|\bramping\b|big mana|land drop"),
    ("card draw", r"\bdraw\b|card advantage|refuel|\bcantrip"),
    ("tutor", r"\btutor\b|search for|find the|consistent"),
    ("removal", r"\bremoval\b|destroy|\bkill\b|\bremove\b|answer(s)? to|interact"),
    ("board wipe", r"board wipe|\bwipe\b|\bwrath\b|sweeper|reset the board"),
    ("counterspell", r"counterspell|counter spells|\bcounter magic\b|permission"),
    ("recursion", r"recur|graveyard|reanimat|bring back|return .* from the yard"),
    ("sacrifice", r"sacrific|\bsac\b|aristocrat"),
    ("token maker", r"\btokens?\b|go wide|\bswarm\b|army|make a lot of"),
    ("counters", r"\+1/\+1|\bcounters\b|\bproliferate\b"),
    ("lifegain", r"life ?gain|gain life|\blifelink\b"),
    ("protection", r"protect|hexproof|indestructible|resilien"),
    ("untapper", r"\buntap"),
    ("cost reduction", r"cheaper|cost reduction|discount"),
    ("evasion", r"evasion|flying|trample|unblockable|\bmenace\b"),
)


def goal_roles_of(goal: str) -> list[str]:
    """What the goal is asking for, read from natural language."""
    low = (goal or "").lower()
    return [name for name, pattern in GOAL_PATTERNS if re.search(pattern, low)]


# Similarity bands. Tuned against this collection: nomic-embed-text puts
# genuinely-on-theme cards around 0.62+, and everything is above 0.35 because
# all Magic text is similar to all other Magic text.
STRONG = 0.62
FAIR = 0.55

# How much doing the requested job is worth against raw similarity. Two matched
# roles outweigh roughly a 12-point similarity gap, which is enough to lift a
# real removal spell over a vaguely-similar artifact.
ROLE_BONUS = 0.06

STOPWORDS = {
    "the", "and", "for", "with", "that", "this", "then", "into", "your", "you",
    "from", "them", "they", "have", "has", "are", "can", "all", "out", "one",
    "make", "makes", "lot", "lots", "want", "wants", "deck", "cards", "card",
    "play", "plays", "win", "wins", "winning", "game", "games", "turn", "turns",
    "way", "get", "gets", "put", "puts", "very", "some", "more", "most", "just",
    "like", "than", "when", "what", "who", "how", "but", "not", "its",
}


def roles_of(text: str | None) -> list[str]:
    if not text:
        return []
    low = text.lower()
    return [name for name, pattern in ROLES if re.search(pattern, low)]


def keywords(text: str) -> set[str]:
    words = re.findall(r"[a-z][a-z'-]{2,}", (text or "").lower())
    return {w for w in words if w not in STOPWORDS}


def _colors_ok(identity: str, allowed: str | None) -> bool:
    """Colour identity must be a subset of what the deck can support."""
    if not allowed:
        return True
    return set(identity or "") <= set(allowed.upper())


def search(conn: sqlite3.Connection, goal: str, *, colors: str | None = None,
           fmt: str | None = None, exclude_deck: int | None = None,
           hide_committed: bool = False, limit: int = 30) -> dict[str, Any]:
    """Rank owned cards against a plain-language goal."""
    if not goal.strip():
        raise ValueError("Describe what you want the deck to do.")

    state = embeddings.status(conn)
    if not state["ready"]:
        raise embeddings.EmbeddingError(
            "No embeddings have been built yet. Build the index first — it "
            "takes about two minutes for a collection this size.")

    query_vector = embeddings.embed([goal])[0]
    # Pull more than asked for, so filtering does not leave a short list.
    index = embeddings.Index.load(conn)
    hits = index.search(query_vector, top=min(len(index), max(limit * 8, 200)))

    goal_roles = set(goal_roles_of(goal))
    goal_words = keywords(goal)

    rows = _card_rows(conn, [oid for oid, _ in hits], fmt)
    committed = _committed(conn)
    in_deck = _deck_members(conn, exclude_deck) if exclude_deck else set()

    results: list[dict[str, Any]] = []
    for oracle_id, score in hits:
        card = rows.get(oracle_id)
        if card is None:
            continue
        if oracle_id in in_deck:
            continue
        if not _colors_ok(card["color_identity"], colors):
            continue
        if fmt and not _legal(card["legality"]):
            continue
        if hide_committed and oracle_id in committed:
            continue

        card_roles = roles_of(card["oracle_text"])
        shared_roles = [r for r in card_roles if r in goal_roles]
        shared_words = sorted(goal_words & keywords(card["oracle_text"] or ""))[:4]

        # Pure similarity ranked Metalwork Colossus above every removal spell
        # for "I need cheap removal": short goals embed vaguely, and a card
        # that demonstrably does the requested job should outrank one that
        # merely reads like the sentence. Reported separately from match_pct so
        # the semantic score stays honest.
        rank_score = score + ROLE_BONUS * min(len(shared_roles), 2)

        results.append({
            "rank_score": round(rank_score, 4),
            "oracle_id": oracle_id,
            "card_id": card["card_id"],
            "name": card["name"],
            "mana_cost": card["mana_cost"],
            "mana_value": card["mana_value"],
            "type_line": card["type_line"],
            "color_identity": card["color_identity"],
            "owned": card["owned"],
            "price_usd": card["price_usd"],
            "score": round(score, 4),
            "match_pct": round(score * 100),
            "roles": card_roles,
            "strength": _strength(score),
            "reason": _reason(score, shared_roles, card_roles, shared_words, goal_roles),
            "weakness": _weakness(score, shared_roles, card_roles, shared_words, goal_roles),
            "committed_to": committed.get(oracle_id, []),
        })
    results.sort(key=lambda r: -r["rank_score"])
    results = results[:limit]

    return {
        "goal": goal,
        "goal_roles": sorted(goal_roles),
        "searched": len(index),
        "results": results,
        "model": state["model"],
    }


def _strength(score: float) -> str:
    if score >= STRONG:
        return "strong"
    if score >= FAIR:
        return "fair"
    return "weak"


def _reason(score: float, shared_roles: list[str], card_roles: list[str],
            shared_words: list[str], goal_roles: set[str]) -> str:
    """Say what actually caused this card to surface."""
    if shared_roles:
        roles = " and ".join(shared_roles)
        if score >= STRONG:
            return f"Does {roles}, which is what you asked for, and its rules text reads like your description."
        return f"Does {roles}, which is what you asked for."
    if score >= STRONG:
        if shared_words:
            return ("Its rules text closely matches how you described the plan — "
                    f"shares {', '.join(shared_words)}.")
        return "Its rules text closely matches how you described the plan."
    if card_roles:
        return f"Surfaced because it does {' and '.join(card_roles[:2])}."
    if shared_words:
        return f"Loosely related wording — shares {', '.join(shared_words)}."
    return "Surfaced on overall similarity alone."


def _weakness(score: float, shared_roles: list[str], card_roles: list[str],
              shared_words: list[str], goal_roles: set[str]) -> str | None:
    """Name what is wrong with a weak match rather than hiding it.

    Returning None means the match needs no caveat. The bar for *claiming* a
    card does not do something is deliberately high: telling the user that
    Eaten Alive is "not a sacrifice card" because a regex wanted a colon is
    worse than saying nothing."""
    if shared_roles:
        return None
    # Strong similarity plus shared vocabulary is evidence enough; the role
    # patterns are a floor, not an oracle.
    if score >= STRONG and shared_words:
        return None
    if score >= STRONG:
        if goal_roles:
            return (f"Reads like your description, but does not obviously do "
                    f"{' or '.join(sorted(goal_roles)[:2])}. Worth checking.")
        return None
    if score < FAIR:
        if card_roles:
            return (f"Weak match. Surfaced because it does {card_roles[0]}, "
                    f"not because it fits the theme.")
        return "Weak match on wording alone — check it actually does what you need."
    if goal_roles:
        return (f"Partial match — does not obviously do "
                f"{' or '.join(sorted(goal_roles)[:2])}.")
    return "Partial match — the wording is close but not the same job."


# --------------------------------------------------------------------------- #

def _card_rows(conn: sqlite3.Connection, oracle_ids: list[str],
               fmt: str | None = None) -> dict[str, Any]:
    """Cheap fields for the candidate cards.

    Legality is read with json_extract from ONE printing, not MIN(raw) across
    all of them: MIN over a text column reads every value, and pulling the full
    Scryfall blob for 200 cards moved a megabyte of JSON to answer a
    one-field question."""
    if not oracle_ids:
        return {}
    legal_expr = "NULL AS legality"
    if fmt:
        legal_expr = ("(SELECT json_extract(c5.raw, '$.legalities.' || ?1) "
                      " FROM cards c5 WHERE c5.oracle_id = c.oracle_id "
                      "   AND c5.digital = 0 LIMIT 1) AS legality")

    out: dict[str, Any] = {}
    for start in range(0, len(oracle_ids), 400):
        chunk = oracle_ids[start:start + 400]
        params: list[Any] = ([fmt.lower()] if fmt else []) + chunk
        marks = ",".join("?" * len(chunk))
        rows = conn.execute(f"""
            SELECT c.oracle_id,
                   MIN(c.name)            AS name,
                   MIN(c.mana_cost)       AS mana_cost,
                   MIN(c.mana_value)      AS mana_value,
                   MIN(c.type_line)       AS type_line,
                   MIN(c.oracle_text)     AS oracle_text,
                   MIN(c.color_identity)  AS color_identity,
                   MIN(c.price_usd)       AS price_usd,
                   (SELECT c8.id FROM cards c8
                     WHERE c8.oracle_id = c.oracle_id AND c8.digital = 0
                       AND c8.image_normal IS NOT NULL
                     ORDER BY c8.released_at DESC LIMIT 1) AS card_id,
                   {legal_expr},
                   (SELECT COUNT(*) FROM copies cp JOIN cards c2 ON c2.id=cp.card_id
                     WHERE c2.oracle_id = c.oracle_id) AS owned
            FROM cards c
            WHERE c.oracle_id IN ({marks}) AND c.digital = 0
            GROUP BY c.oracle_id""", params).fetchall()
        for r in rows:
            out[r["oracle_id"]] = r
    return out


def _legal(legality: str | None) -> bool:
    # An unknown legality is treated as legal: a missing field should not
    # quietly hide a card you own.
    return (legality or "legal") in ("legal", "restricted")


def _committed(conn: sqlite3.Connection) -> dict[str, list[str]]:
    """Which decks already use each card, so a suggestion can say so."""
    rows = conn.execute("""
        SELECT dc.oracle_id, d.name FROM deck_cards dc
        JOIN decks d ON d.id = dc.deck_id WHERE dc.wishlist = 0""").fetchall()
    out: dict[str, list[str]] = {}
    for r in rows:
        out.setdefault(r["oracle_id"], []).append(r["name"])
    return out


def _deck_members(conn: sqlite3.Connection, deck_id: int) -> set[str]:
    return {r[0] for r in conn.execute(
        "SELECT oracle_id FROM deck_cards WHERE deck_id=?", (deck_id,))}
